### ISSUE TITLE
[Question] 서비스 계층의 테스트 코드

### ISSUE THREAD

**Issue by jang-namu** [inu-appcenter/server-study-15.5#103]
[8bbf45b](https://github.com/inu-appcenter/server-study-15.5/pull/98/commits/8bbf45b9e7e068621432573d924f3208208a80ae)에 마지막에

'서비스 계층의 테스트의 경우 userId의 생성(GenerationType.IDENTITY)을 위해 DB에 save하는 로직 수정필요'
질문이 있습니다. User 엔티티를 반환받아야 하는데, ControllerTest에서 그랬던 것 처럼 Return Object를 빌더나 생성자를 통해 직접 생성할 수 없는 상태입니다.

<img width="933" alt="image" src="https://github.com/inu-appcenter/server-study-15.5/assets/121238128/a0db2551-5934-4025-b539-f759fdb16b83">

Repository가 MockBean이기 때문에 save()를 수행해도 실제 엔티티가 DB에 저장되는 것은 아닙니다.
그 근거로 userId는 여전히 null입니다. (위 테스트코드는 정상적으로 통과합니다.)

어떤식으로 작성해야 현재 코드베이스(User엔티티의 생성자 및 userId 생성규칙)를 유지하며 실제 DB와의 상호작용이 필요하지 않은
단위 테스트를 작성할 수 있을까요??

<img width="1052" alt="스크린샷 2023-12-01 오후 4 19 08" src="https://github.com/inu-appcenter/server-study-15.5/assets/121238128/9c5d7bb3-5b9c-438f-8cb2-59492780efdd">

userId는 null입니다.

_Originally posted by @jang-namu in https://github.com/inu-appcenter/server-study-15.5/issues/98#issuecomment-1835600171_

**Comment by NARUBROWN** [comment]
테스트 하려는 Object Property가 무엇인지에 대해 생각해봐야 할 것 같아.

일단 나는 userId가 null 값이어야 하고,
우리가 이를 테스트 해볼 필요가 없다고 생각해.

왜냐면 Service Layer가 id의 생성에 관여하지 않기 때문이야. 

그래도 테스트 해보고 싶다면, 정규식을 통해 value가 id 생성 조건을 만족하는지 확인하는 것으로 검증 로직을 구성해 볼 수 있을 것 같네

세 줄 요약
1. GenerationType.IDENTITY의 책임은 어디에 있는가?
2. SQL에 의존하여 생성되는 Field를 테스트해야 하는 이유가 있을까?
3. 그래도 테스트해보고 싶다면 정규식을 활용해 볼 수 있을 것 같다...

관련 내용을 찾아보고 답변해주고 싶었지만..  관련 내용을 찾을 수 없어서 내 생각으로만 적었어
도움이 됐으면 좋겠다!
