### ISSUE TITLE
[공유] swagger-2.9.2 사용 시, java.lang.NumberFormatException(해결법)

### ISSUE THREAD

**Issue by jang-namu** [inu-appcenter/server-study-15.5#67]
## 📋 이슈 내용
swagger-2.9.2 사용 시 흔하게 일어나는 일로 swagger-ui에 접속하면 다음과 같은 예외가 발생합니다.

![image](https://github.com/inu-appcenter/server-study-15.5/assets/121238128/be8a1d9e-2db5-4e6c-bf30-7ee57f6175f0)

간단한 해결법은 dependencies에 swagger 구버전의 어노테이션과 모델을 추가해 사용하는 것이라 합니다.

<img width="808" alt="image" src="https://github.com/inu-appcenter/server-study-15.5/assets/121238128/9bf22bd4-b54d-428d-becc-4c3765067ec9">

## 📚 레퍼런스
[swagger2 java.lang.NumberFormatException](https://earth-95.tistory.com/114)

## 추가
또는 Swagger가 명세하는 대상이 int, float와 같은 원시 자료형일 경우.
null값이 될 수 없으므로 발생하기도 한다고 합니다. 이 경우, @ApiParam에 'example = 1' 과 같은 필드를 추가하면 경고가 사라집니다.

**Comment by squidjiny** [comment]
3을 쓰자.

**Comment by sukangpunch** [comment]
좋은 정보 감사합니다!
