### ISSUE TITLE
[Refact] Service & Controller 코드 수정

### ISSUE THREAD

**Issue by sukangpunch** [inu-appcenter/server-study-15.5#68]
## ✅ 체크리스트
- [x] Time 슈퍼클래스 사용
- [x] Swagger 꾸미기
- [x] isCompleted 필드 이름 바꾸기
- [x] 메서드 명명규칙 준수하기
- [x] ApiModelProperty 추가

**Comment by squidjiny** [comment]
메ㅔㅔㅔㅔㅔ롱

**Comment by sukangpunch** [comment]
> 어른답게.
