### ISSUE TITLE
[Question] final과 unmodifiable~, 방어적 복사의 사용

### ISSUE THREAD

**Issue by jang-namu** [inu-appcenter/server-study-15.5#75]
## 📋 이슈 내용
지난 pull request #51에서 
unmodifiable~에 대한 피드백을 받았습니다.
관련해서 찾다 보니 [방어적 복사와 unmodifiable](https://tecoble.techcourse.co.kr/post/2021-04-26-defensive-copy-vs-unmodifiable/) 해당 블로그의 아티클을 보게되었고 궁금증이 생겼습니다.

평소 final 키워드를 비롯해, 객체의 불변성, 일관성 등을 제공하기 위한 기능들의 사용을 깊게 고민하지 못 했던 것 같습니다.
각각 언제 사용하는지, 또 어떻게 사용하면 좋을지에 대해 의견을 묻고 싶습니다.
관련하여 많은 의견 부탁드립니다.

**Comment by Juser0** [comment]
@jang-namu 
**저는 final 키워드는 객체의 불변성과 관련된 상황에서 사용하고 있습니다.**
제가 사용하는 경우라고 한다면 변하지 않아야 하는 상황이 대표적이고, 파라미터에도 붙이는 경우도 가끔 있습니다.
- 생성자 주입 방식으로 의존성 주입을 구현하는 경우 (다른 주입 방법이라도 final 키워드는 있어야 한다고 생각합니다)
- 상수처럼 확실하게 불변의 값을 선언하는 경우 (@Value 어노테이션으로 환경설정 파일에서 가져오는 경우에는 모르겠지만, 정해진 값이 변하지 않아야 하는 (DEFAULT_RESPONSE_MESSAGE = "API가 실행되었습니다" 등) 상황

저도 final 키워드에 대해 많이 고민을 했었는데, **개인적으로 parameter에 final 키워드를 붙이는 것은 '명시' 그 이상, 그 이하도 아니라고 생각합니다.**
이때, 명시의 의미는 '해당 파라미터를 변경할 수 없다'라는 것을 알려주는 것입니다.
만약, controller method에 (@RequestBody final RequestDto dto)인 경우 dto를 선언, 변경할 수 없지만 그렇게 작성하는 개발자는 많이 없기도 하고, 그런 폐쇄적인 활용을 신경쓰는 경우 변경과 선언에 있어서 상당히 제약을 둔 형태로 dto를 생성할 것이라 생각합니다.

그래서 final 키워드를 모든 곳에 붙이고, final 키워드를 위해 매개변수가 있는 생성자를 구현하는 경우는 비효율적이라고 생각합니다. 
final 키워드를 앞서 말한 '해당 파라미터를 변경할 수 없다'라는 의미를 부여하고 싶다면
controller method의 parameter에서만 명시하는 방향으로 추천하고 싶습니다 (개인적으로)
왜냐하면, 유효성 검사와 같은 원리로 모든 레이어의 parameter에 final 키워드가 붙어 불변성을 명시하는 것은 모든 레이어에서 유효성 검사를 진행하는 것이 비효율적인 것과 유사하다고 보기 때문입니다.

만약, 명시의 의미도 주석이나 굳이 할 필요가 없다 판단한다면, 정말 필요한 경우에서만 사용하시면 좋을 것 같습니다!

> ref [okky link](https://okky.kr/questions/682182)

**Comment by Juser0** [comment]
@jang-namu 
방어적 복사와 unmodifiable에 대한 내용도 이슈를 보고 처음 읽어봤습니다.
값을 복사하는데 있어서 고려하는 것은 상당히 중요하다고 생각합니다.

만약, stream 등의 방법으로 새로운 List를 생성하는 경우 unmodifiable / immutable한 속성을 주는 것은 준다면 더 좋다고 판단했습니다.
마치 Transactional에 readOnly 키워드를 붙여 복구 스냅샷을 만들지 않아 메모리를 절약하는 사례처럼 말이죠.

**Comment by jang-namu** [comment]
좋은 답변 감사합니다.
상수나 Spring에서의 빈 주입, 필드 주입과 같은 형태를 제외하고 final 키워드가 가지는 의미를 잘 모르겠는데 답변해주신 내용이 많이 도움이 됐습니다. 다만 아직까지도 메소드 파라미터나 반환값 등에 final을 붙이는 것이 좋은 습관인지에 대해서는 의문이 남는건 어쩔 수 없네요.
어차피 자바는 전부 call-by-value이고 객체의 참조는 바뀌지 않는 것을 보장하니 final을 사용하는 것이 메서드 내부의 객체 변경에 대한 안정성과 final 키워드를 안 붙임으로써 얻는 가독성(사실 이 부분도 final 키워드가 가독성을 헤치는가 하는 의문이 있긴 합니다. 반대로 가독성이 좋아진다는 의견이 있을수도..) 사이에서 헤매게되네요.
final 키워드를 통해 '해당 파라미터를 변경할 수 없다'라는 의미를 부여하는 것에는 동의하나 마땅한 실 사례가 생각나지는 않네요 ㅠ

혹시 언급하신 내용 중 파라미터에 dto가 아닌 Long이나 Integer 타입이라면 어떻게 하는게 좋을까요??

**Comment by Juser0** [comment]
> 좋은 답변 감사합니다. 상수나 Spring에서의 빈 주입, 필드 주입과 같은 형태를 제외하고 final 키워드가 가지는 의미를 잘 모르겠는데 답변해주신 내용이 많이 도움이 됐습니다. 다만 아직까지도 메소드 파라미터나 반환값 등에 final을 붙이는 것이 좋은 습관인지에 대해서는 의문이 남는건 어쩔 수 없네요. 어차피 자바는 전부 call-by-value이고 객체의 참조는 바뀌지 않는 것을 보장하니 final을 사용하는 것이 메서드 내부의 객체 변경에 대한 안정성과 final 키워드를 안 붙임으로써 얻는 가독성(사실 이 부분도 final 키워드가 가독성을 헤치는가 하는 의문이 있긴 합니다. 반대로 가독성이 좋아진다는 의견이 있을수도..) 사이에서 헤매게되네요. final 키워드를 통해 '해당 파라미터를 변경할 수 없다'라는 의미를 부여하는 것에는 동의하나 마땅한 실 사례가 생각나지는 않네요 ㅠ
> 
> 혹시 언급하신 내용 중 파라미터에 dto가 아닌 Long이나 Integer 타입이라면 어떻게 하는게 좋을까요??

파라미터가 dto가 아닌 Long이나 Integer타입의 경우에도 final 키워드의 의미는 앞서 이야기한 내용과 똑같이 생각합니다.
개인적으로 dto는 내부 요소를 확인하지 않으면 변경할 수도 있지만, Long이나 Integer타입 같이 reference 타입이지만 primitive 타입의 역할을 아는 경우에는 변경 가능성이 없다고 판단해서 굳이 붙일 필요가 없어 보입니다.
